config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # CRUD
  # Create, Read, Update, Delete
  # verb 'path', to: 'controller#action'
  # Read all the tasks
  get '/tasks', to: 'tasks#index'
  # Create a task
  get '/tasks/new', to: 'tasks#new'
  # Read one task
  get '/tasks/:id', to: 'tasks#show', as: :task
  # Create a task
  post '/tasks', to: 'tasks#create'
  # Update a task
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch '/tasks/:id', to: 'tasks#update'
  # Delete a task
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  # all tasks
  def index
    @tasks = Task.all
  end
  # display task
  def show
  end
  # new task
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    # no need for app/views/restaurants/create.html.erb
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)

    # no need for app/views/restaurants/create.html.erb
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_for(@task) do |f| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<p><%= link_to "Back to list", tasks_path %></p>

app/views/tasks/index.html.erb
<h1>All tasks</h1>
<ul>
<% @tasks.each do |task| %>
<li><%= link_to task.title, task_path(task) %></li>
<% end %>
</ul>

<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<p><%= link_to "Back to list", tasks_path %></p>

app/views/tasks/show.html.erb
<div class="task-title"><h2><%= @task.title %></h2>
<%= link_to delete_task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure you want to delete '#{@task.title}'?" } do %>
            <i class="fas fa-trash-alt"></i>
            <% end %>&ensp;
            <div class="btn btn-edit">
              <%= link_to edit_task_path do %>
              <i class="fas fa-edit"> Edit this task</i>
              <% end %>
            </div>
          </div>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>
<hr>
  <%= link_to tasks_path do %>
  <i class="fas fa-undo">&ensp;Back to list</i>
  <% end %>